# Generated by Django 4.1.2 on 2023-02-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_usermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=200),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default='LastName', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default='PY7DMegfFyM', max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
