# Generated by Django 4.1.2 on 2023-02-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_usermodel_first_name_usermodel_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='short_id',
            field=models.CharField(default='fjZAx3Pezgj', max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
