# Generated by Django 4.1.2 on 2023-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_usermodel_id_usermodel_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='short_id',
            field=models.CharField(default='djyvDpeZwBg', max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
