# Generated by Django 4.1.2 on 2023-02-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_usermodel_short_id_usermodel_id'),
    ]

    operations = [
    ]
