# Generated by Django 4.1.2 on 2023-02-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20230216_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='short_id',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
