# Generated by Django 4.1.2 on 2023-02-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_usermodel_id_alter_usermodel_short_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='short_id',
            field=models.CharField(default='kLprbqPmDJU5', max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
